### ISSUE TITLE
Program doesn't end

### ISSUE THREAD

**Issue by ghalib5000** [ghalib5000/My-Twitter-Bot#1]
so the program is running fine and everything and it's updating the image number on the firebase database but only once..... that is to say that the program doesn't end after been run once and it just doesn't end 
![image](https://user-images.githubusercontent.com/24367329/64078049-b3f5ef00-ccef-11e9-9d87-d1e8a201dd24.png)

this is the line of code that makes the program to run indefinatly 
![image](https://user-images.githubusercontent.com/24367329/64078061-cb34dc80-ccef-11e9-82ef-66535d951aa9.png)

this is the result it's giving but i don't want that

![image](https://user-images.githubusercontent.com/24367329/64078066-e1429d00-ccef-11e9-9998-b00d9fb898b3.png)

this is the desired result that i want

**Comment by WajahatAliAbid** [comment]
Use this code snippet.
```javascript
const database = firebase.database();
let data = await database.ref().once('value');
database.goOffline();
```

**Comment by ghalib5000** [comment]
0o thanks
